FROM registry.cn-hangzhou.aliyuncs.com/ziyouvip/python:3.11-alpine
WORKDIR /code
COPY docker-generateconfig/env-requirements.txt requirements.txt
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "/code/docker-generateconfig/env.py"]
